export const Users = [
  {
    id:1,
    profilePicture: "profile pics/1.jpg",
    username: "Rohit",
  },
  {
    id:2,
    profilePicture: "profile pics/2.jpg",
    username: "Sonika",
  },
  {
    id:3,
    profilePicture: "profile pics/3.jpg",
    username: "Samee",
  },
  {
    id:4,
    profilePicture: "profile pics/4.jpg",
    username: "Vishnu",
  },
  {
    id:5,
    profilePicture: "profile pics/5.jpg",
    username: "Vastav",
  },
  {
    id:6,
    profilePicture: "profile pics/6.jpg",
    username: "Konda Lohit",
  },
  {
    id:7,
    profilePicture: "profile pics/7.jpg",
    username: "Vinuthna",
  },
  {
    id:8,
    profilePicture: "profile pics/8.jpg",
    username: "Satti",
  },
  {
    id:9,
    profilePicture: "profile pics/9.jpg",
    username: "Jenny",
  },
  {
    id:10,
    profilePicture: "profile pics/10.jpg",
    username: "Rama Krishna",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "posts/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "posts/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "posts/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "posts/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "posts/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "posts/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "posts/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "posts/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "posts/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "posts/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
